### ISSUE TITLE
ex-statsd must be required manually

### ISSUE THREAD

**Issue by vsmart** [jeffweiss/plug_statsd#6]
Hi, 
I had to add ex-statsd to the mix.exs file manually to get it to load - the dependency wasn't fetched by plug-statsd. 
Any ideas why that was the case? It is expected to be fetched by this plug, right?

**Comment by joshuap** [comment]
+1. I'm thinking README.md should be updated with the following deps under [Usage](https://github.com/jeffweiss/plug_statsd/blob/master/README.md#usage-1)

``` elixir
defp deps do
  [{:ex_statsd, "~> 0.5"},
    {:plug_statsd, ">= 0.2.1"}]
end
```

@jeffweiss I'm happy to submit a PR if you agree.

**Comment by jeffweiss** [comment]
@vsmart I'm terribly sorry for the confusion! I have fixed this in the docs for 0.3.1.

You'll need a deps section that looks like this:

``` elixir
defp deps do
  [
    {:plug_statsd, "~> 0.3"},
    {:ex_statsd, "~> 0.5"},
  ]
end
```

You should also update your applications list to include the statsd plug and the backend:

``` elixir
def application do
  [applications: [:plug_statsd, :ex_statsd]]
end
```

Because plug_statsd supports two backends ([ex_statsd](https://github.com/CargoSense/ex_statsd) and [statsderl](https://github.com/lpgauth/statsderl)), it won't automatically choose a statsd backend for you. So, yes, it's expected that you'll need to manually add either ex_statsd or statsderl to both your dependencies and your applications to start. 

Adding dependent applications to the `applications` section needs to be done for an proper [exrm](https://github.com/bitwalker/exrm) release anyway, so hopefully adding it to `deps` shouldn't be too great of a burden.

**Comment by joshuap** [comment]
:+1:

**Comment by vsmart** [comment]
Great, thank you!
